azure:
  cosmos:
    uri: https://127.0.0.1:8081
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: Assets
    connection-mode: gateway
    consistency-level: eventual
    validate-uri: false
